"""LLM client wrapper (Sarvam or Groq backend).

Abstracts the LLM call behind a single interface so the model/provider
can be swapped without touching pipeline logic (per instructions.md).

Provider selection: explicit `provider` arg wins; otherwise auto-detects
Groq if GROQ_API_KEY is set (added as a more reliable fallback after
Sarvam's sarvam-105b showed a high empty-response rate under time
pressure -- see DECISIONS.md), else falls back to Sarvam.
"""

import json
import time
import os
import hashlib
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

DEFAULT_SARVAM_MODEL = "sarvam-105b"
DEFAULT_GROQ_MODEL = "openai/gpt-oss-120b"  # verified available on this account; llama-3.3-70b-versatile 404s


class LLMClient:
    """Wrapper around an LLM API (Sarvam or Groq) with caching."""

    def __init__(self, model: str = None, use_cache: bool = True,
                request_timeout: float = 30.0, provider: str = None):
        self.provider = provider or ("groq" if os.getenv("GROQ_API_KEY") else "sarvam")

        if self.provider == "groq":
            from groq import Groq

            api_key = os.getenv("GROQ_API_KEY")
            if not api_key:
                raise ValueError("GROQ_API_KEY not set. Check your .env file.")
            self.client = Groq(api_key=api_key, timeout=request_timeout)
            self.model = model or DEFAULT_GROQ_MODEL
        else:
            from sarvamai import SarvamAI

            api_key = os.getenv("SARVAM_API_KEY")
            if not api_key:
                raise ValueError("SARVAM_API_KEY not set. Check your .env file.")
            # Native httpx-backed timeout, not a thread-pool hack: a hung connection
            # now actually raises after `request_timeout` seconds instead of blocking
            # forever (see generate()'s history/comment for why the old approach broke).
            self.client = SarvamAI(api_subscription_key=api_key, timeout=request_timeout)
            self.model = model or DEFAULT_SARVAM_MODEL

        self._usage_log = []

        # Cache setup -- keyed by provider+model too, so switching backends
        # doesn't silently reuse a cached answer generated by a different model.
        self._use_cache = use_cache
        self._cache_path = Path(__file__).parent.parent / "data" / "llm_cache.json"
        self._cache = self._load_cache()
    
    def _load_cache(self) -> dict:
        """Load LLM response cache from disk."""
        if self._use_cache and self._cache_path.exists():
            try:
                with open(self._cache_path) as f:
                    return json.load(f)
            except:
                pass
        return {}
    
    def _save_cache(self):
        """Save LLM response cache to disk."""
        if self._use_cache:
            try:
                with open(self._cache_path, "w") as f:
                    json.dump(self._cache, f, indent=2)
            except:
                pass
    
    def _get_cache_key(self, prompt: str, system_instruction: str = None) -> str:
        """Generate cache key from provider+model+prompt+system instruction.

        Including provider/model means switching backends never silently
        reuses another model's cached answer for the same prompt text.
        """
        content = f"{self.provider}:{self.model}|{system_instruction or ''}|{prompt}"
        return hashlib.md5(content.encode()).hexdigest()

    def generate(self, prompt: str, system_instruction: str = None, max_attempts: int = 2) -> str:
        """Generate a response from the LLM with timeout and caching.

        Single retry layer (previously this had a decorator retrying 3x
        wrapping an inner loop retrying 3x -- up to 9 attempts compounding
        with a broken thread-based timeout, which could make one call take
        effectively unbounded time). Relies on the SarvamAI client's own
        httpx-backed `timeout` (set in __init__) to fail fast on a hung
        connection, instead of a ThreadPoolExecutor timeout that doesn't
        actually bound wall-clock time (see git history).

        Args:
            prompt: User prompt
            system_instruction: System instruction (optional)
            max_attempts: Total attempts (including the first) before giving up.

        Returns:
            Generated response or None if failed
        """
        cache_key = self._get_cache_key(prompt, system_instruction)
        if cache_key in self._cache:
            print("[LLM] Cache hit")
            return self._cache[cache_key]

        messages = []
        if system_instruction:
            messages.append({"role": "system", "content": system_instruction})
        messages.append({"role": "user", "content": prompt})

        for attempt in range(max_attempts):
            try:
                if self.provider == "groq":
                    response = self.client.chat.completions.create(
                        model=self.model, messages=messages
                    )
                else:
                    # reasoning_effort="low": sarvam-105b is a reasoning model that
                    # can burn its whole output budget on internal thinking tokens
                    # on longer prompts, leaving an empty final `content` (a known
                    # quirk -- see DECISIONS.md). Forcing low effort measurably cuts
                    # latency in testing and should reduce how often this happens.
                    response = self.client.chat.completions(
                        model=self.model, messages=messages, reasoning_effort="low"
                    )

                if hasattr(response, "usage") and response.usage:
                    self._usage_log.append({
                        "prompt_tokens": getattr(response.usage, "prompt_tokens", 0),
                        "completion_tokens": getattr(response.usage, "completion_tokens", 0),
                    })

                raw_response = response.choices[0].message.content
                if raw_response is not None:
                    result = self._strip_thinking(raw_response)
                    self._cache[cache_key] = result
                    self._save_cache()
                    return result
                print(f"[LLM] Empty response (attempt {attempt + 1}/{max_attempts})")

            except Exception as e:
                print(f"[LLM] Error: {e} (attempt {attempt + 1}/{max_attempts})")

            if attempt < max_attempts - 1:
                time.sleep(1)

        return None

    def _strip_thinking(self, text: str) -> str:
        """Strip chain-of-thought/reasoning from LLM response.

        Many LLMs output their reasoning before the final answer.
        This function extracts only the actual reply.
        """
        # Look for common thinking markers
        markers = [
            "\nRaw thought process:",
            "\nLet me think:",
            "\nMy reasoning:",
            "\nStep-by-step:",
            "\nChain of thought:",
            "\nThinking:",
            "\nAnalysis:",
            "\nLet me analyze:",
        ]

        for marker in markers:
            if marker in text:
                text = text.split(marker)[0]

        # Also strip if response starts with "Drafting:" or similar
        lines = text.strip().split("\n")
        # Find first line that looks like actual content (not a label)
        start_idx = 0
        for i, line in enumerate(lines):
            stripped = line.strip()
            if stripped and not stripped.endswith(":") and not stripped.startswith("-"):
                start_idx = i
                break

        return "\n".join(lines[start_idx:]).strip()

    def generate_structured(self, prompt: str, system_instruction: str = None) -> dict:
        """Generate a JSON-structured response from the LLM."""
        response_text = self.generate(prompt, system_instruction)
        if response_text is None:
            return {"intent": "unclear", "confidence": 0.0}

        try:
            # Strip markdown code fences if present
            cleaned = response_text.strip()
            if cleaned.startswith("```"):
                cleaned = cleaned.split("\n", 1)[1]
            if cleaned.endswith("```"):
                cleaned = cleaned.rsplit("```", 1)[0]
            return json.loads(cleaned.strip())
        except json.JSONDecodeError:
            # Try to extract JSON from text
            import re
            match = re.search(r'\{[^}]+\}', cleaned, re.DOTALL)
            if match:
                try:
                    return json.loads(match.group())
                except json.JSONDecodeError:
                    pass
            return {"intent": "unclear", "confidence": 0.0}

    @property
    def total_tokens_used(self) -> dict:
        """Return cumulative token usage."""
        total_prompt = sum(u["prompt_tokens"] for u in self._usage_log)
        total_completion = sum(u["completion_tokens"] for u in self._usage_log)
        return {
            "prompt_tokens": total_prompt,
            "completion_tokens": total_completion,
            "total_tokens": total_prompt + total_completion,
            "num_requests": len(self._usage_log),
        }
